version: "3.8"

services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      sb-postgre:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=student
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432'
    networks:
      sb-postgre:

networks:
  sb-postgre: