name: "CI"
on:
  push:
    branches:
      - main
env:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: sb-postgre-docker

    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: baicham/baicham:latest

      - name: Deploy with Docker compose
        run: |
          docker-compose up -d